"""Init

Revision ID: 0fe6a08fb77f
Revises: c30a3fd64f86
Create Date: 2023-03-05 14:17:10.158687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe6a08fb77f'
down_revision = 'c30a3fd64f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
